### ISSUE TITLE
File name matching

### ISSUE THREAD

**Issue by LiyingCheng95** [TsinghuaDatabaseGroup/nvBench#2]
How to match the id from html file name in the nvBench_VegaLite folder (e.g. [VIS_1.html](https://github.com/TsinghuaDatabaseGroup/nvBench/blob/main/nvBench_VegaLite/VIS_1.html)) to the key (the id of the (NL, VIS) pair in NVBench benchmark)?

**Comment by Thanksyy** [comment]
Hi, sorry for the confusion. Actually, the `(NL, VIS) ID:` key under the `properties` field of the HTML file is the JSON key of the `NVBench.json`.

**Comment by LiyingCheng95** [comment]
Ok got it, thanks!
